### ISSUE TITLE
How to get Ledger Nano X firmware `1.2.5-1.5` for NervOS?

### ISSUE THREAD

**Issue by yuche** [obsidiansystems/ledger-app-nervos#164]
I followed the tutorial and tried the Ledger Nano S and it works.
However, the latest firmware version of the Ledger Nano X is `1.2.4-4`, and if I try to install `hw-ckb-app` on this firmware version, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/yuche/Downloads/ledger/lib/python3.7/site-packages/ledgerblue/loadApp.py", line 202, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId)
  File "/Users/yuche/Downloads/ledger/lib/python3.7/site-packages/ledgerblue/deployed.py", line 115, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/Users/yuche/Downloads/ledger/lib/python3.7/site-packages/ledgerblue/comm.py", line 145, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 69d5 (Unknown reason)
```

**Comment by mikereinhart** [comment]
Hello! Unfortunately the Ledger Nano X firmware doesn't allow you to sideload an application onto the device. "Sideloading" is the term used anytime you load an application without Ledger Live. See the note at the bottom of this section of the docs - https://github.com/obsidiansystems/ledger-app-nervos#ledger-app-installation

If you'd like to use the app on the Nano X you'll unfortunately have to wait until it is available in Ledger Live. Ledger distributes development Nano X devices to teams building apps, which is how we've gone about making the app.
